import{a as y,i,t as h,S as L}from"./assets/vendor-CBGxuySl.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))g(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&g(l)}).observe(document,{childList:!0,subtree:!0});function f(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function g(t){if(t.ep)return;t.ep=!0;const s=f(t);fetch(t.href,s)}})();async function d(r,e){return await y.get("https://pixabay.com/api/",{params:{key:"29734383-6ec437d7a0c5df52cef54a0f9",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:16}})}function u(r){return r.map(e=>`<li class="gallery-item">
            <a class="item-link" href="${e.largeImageURL}">
              <img
                class="item-image"
                src="${e.webformatURL}"
                alt="${e.tags}"
              >
            </a>
            <div class="item-stats_container">
              <p class="item-stats"><span>Likes</span>${e.likes}</p>
              <p class="item-stats"><span>Views</span>${e.views}</p>
              <p class="item-stats"><span>Comments</span>${e.comments}</p>
              <p class="item-stats"><span>Downloads</span>${e.downloads}</p>
            </div>
          </li>`).join("")}i.settings({position:"topRight",timeout:5e3,closeOnEscape:!0});function w(){return i.error({title:"Error",message:"Please try again"})}function v(){return i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}function b(){return i.error({message:"Please enter a value!"})}function q(){return i.warning({title:"Warning",message:"We are out of images. Please change the query"})}const S=document.querySelector(".js-form"),c=document.querySelector(".js-gallery"),o=document.querySelector(".js-load-button"),p=document.querySelector(".scroll-up-button");let n,a;console.log(h);const m=new L(".item-link",{captions:!0,captionsData:"alt",captionDelay:250});S.addEventListener("submit",E);o.addEventListener("click",P);p.addEventListener("click",()=>{window.scroll({top:0,behavior:"smooth"})});window.addEventListener("scroll",h(()=>{console.log("scrolled"),window.scrollY>2400?p.classList.remove("scroll-hidden"):p.classList.add("scroll-hidden")},300));function E(r){if(r.preventDefault(),o.classList.contains("is-hidden")||o.classList.add("is-hidden"),n=1,c.innerHTML="",a=r.currentTarget.elements.query.value,a===""){b();return}d(a,n).then(({data:{hits:e}})=>{if(e.length===0){v();return}c.insertAdjacentHTML("beforeend",u(e)),m.refresh(),o.classList.remove("is-hidden"),n++}).catch(()=>w())}function P(){n<=31?d(a,n).then(({data:{hits:r}})=>{c.insertAdjacentHTML("beforeend",u(r)),m.refresh(),n++}):(d(a,n).then(({data:{hits:r}})=>{c.insertAdjacentHTML("beforeend",u(r)),m.refresh()}),o.classList.add("is-hidden"),q())}
//# sourceMappingURL=index.js.map
